version: '3.8'

services:
  price-tracker:
    build: .
    container_name: price-tracker
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data
      - ./config:/app/config
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--enable-source-maps
      - DATABASE_URL=file:/data/tracker.db
      - PORT=3000
      # Notification settings (override with .env)
      - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=${SMTP_FROM}
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK}
      # App settings
      - BASE_URL=${BASE_URL:-http://localhost:3000}
      - SECRET_KEY=${SECRET_KEY:-change-me-in-production}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_DIR=/data/logs
    networks:
      - tracker-network
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:3000/health').then(r => process.exit(r.ok ? 0 : 1)).catch(() => process.exit(1))"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

networks:
  tracker-network:
    driver: bridge

volumes:
  data: